services:
  fe:
    hostname: ival-fe
    container_name: ival-fe
    build:
      context: ./frontend
    ports:
      - "8100:8100"
    working_dir: /usr/src/ionic-app
    volumes:
      - ./frontend:/ionic-app
    depends_on:
      - be
    networks:
      - ionic-nw

  be:
    hostname: ival-be
    container_name: ival-be
    build:
      context: ./bff
    ports:
      - "3000:3000"
    working_dir: /usr/src/bff-app
    volumes:
      - ./bff:/usr/src/bff-app
    networks:
      - ionic-nw

volumes:
  ionicdata:


networks:
  ionic-nw:
    driver: bridge
